name: PR - Validate and Build

permissions: read-all

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - milestoned

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    outputs:
      preview: ${{ steps.check_pr_preview.outputs.preview }}
    steps:
      - name: Check dependabot/fork build
        if: github.secret_source == 'Dependabot' || (github.secret_source == 'None' && github.event.action != 'milestoned')
        uses: Alfresco/alfresco-build-tools/.github/actions/github-require-secrets@bebd6c2fddd0a58ecf7f0acfc511a019f6afc180 # v9.2.0
        with:
          dependabot-error-message: "This PR requires additional validation, please set the milestone to 'Validating' or ask a reviewer to approve it."
          none-error-message: "This PR requires additional validation, please set the milestone to 'Validating'."
      - name: pre-commit
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@bebd6c2fddd0a58ecf7f0acfc511a019f6afc180 # v9.2.0
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@9e9574ef04ea69da568d6249bd69539ccc704e74 # v4.0.0
      - name: Check PR preview
        id: check_pr_preview
        shell: bash
        run: |
          echo "preview=${{ contains(github.event.pull_request.labels.*.name, 'preview') }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # 5.0.0
        with:
          java-version: 21
          distribution: "temurin"

      - name: Set preview version
        if: ${{ needs.pre-checks.outputs.preview == 'true' }}
        run: |
          GITHUB_PR_NUMBER=PR-${{ github.event.pull_request.number }}
          echo 0.0.1-${GITHUB_PR_NUMBER}-${GITHUB_RUN_NUMBER}-SNAPSHOT > VERSION

      - name: Set VERSION env variable
        if: ${{ needs.pre-checks.outputs.preview == 'true' }}
        run: |
          VERSION=$(cat VERSION)
          echo set VERSION=$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update pom files to the new version
        if: ${{ needs.pre-checks.outputs.preview == 'true' }}
        run: mvn -B versions:set -DnewVersion=$VERSION -DprocessAllModules=true -DgenerateBackupPoms=false

      - name: Define Maven Command
        id: define_maven_command
        shell: bash
        run: |
          if [[ $DO_PUSH == 'true' && $SECRET_SOURCE != 'None' ]]
          then
            echo "command=deploy" >> $GITHUB_OUTPUT
          else
            echo "command=install" >> $GITHUB_OUTPUT
          fi
        env:
          DO_PUSH: ${{ needs.pre-checks.outputs.preview }}
          SECRET_SOURCE: ${{ github.secret_source }}

      - name: Build and Test with Maven (and maybe deploy)
        shell: bash
        run: mvn ${{ steps.define_maven_command.outputs.command }} ${{ env.MAVEN_CLI_OPTS}}
        env:
          MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - name: Merge JaCoCo execution files
        shell: bash
        run: mvn jacoco:merge@merge -N

      - name: Generate aggregate coverage report
        shell: bash
        run: mvn jacoco:report -Djacoco.dataFile=${{ github.workspace }}/target/jacoco.exec

      - name: Set SONAR_SCANNER_OPTS
        shell: bash
        run: |
          echo "SONAR_SCANNER_OPTS=sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=activiti -Dsonar.projectKey=Activiti_Activiti -Dsonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco*/jacoco.xml" >> $GITHUB_ENV

      - name: Run SonarCloud analysis
        if: ${{ env.SONAR_TOKEN != '' }}
        shell: bash
        run: mvn ${{ env.SONAR_SCANNER_OPTS }} ${{ env.MAVEN_CLI_OPTS}}
        env:
          MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Echo Longest Test Run
        uses: ./.github/actions/echo-longest-run
