name: Push - Validate, Build and Release

permissions:
  actions: write
  checks: write
  contents: write

on:
  push:
    branches:
      - develop

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.dependabot.outputs.result }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: dependabot check
        id: dependabot
        uses: Alfresco/alfresco-build-tools/.github/actions/github-pr-check-metadata@bebd6c2fddd0a58ecf7f0acfc511a019f6afc180 # v9.2.0
        with:
          gh-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          actor: "dependabot[bot]"
          label: github_actions
      - name: pre-commit
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@bebd6c2fddd0a58ecf7f0acfc511a019f6afc180 # v9.2.0
        with:
          skip_checkout: true
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@9e9574ef04ea69da568d6249bd69539ccc704e74 # v4.0.0

  build:
    runs-on: ubuntu-latest
    needs: pre-checks
    if: ${{ needs.pre-checks.outputs.skip != 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # 5.0.0
        with:
          java-version: 21
          distribution: "temurin"

      - uses: Alfresco/alfresco-build-tools/.github/actions/update-pom-to-next-pre-release@bebd6c2fddd0a58ecf7f0acfc511a019f6afc180 # v9.2.0
        id: update-pom-to-next-version

      - name: Update VERSION file
        run: |
          echo ${{steps.update-pom-to-next-version.outputs.next-prerelease}} > VERSION

      - name: Set VERSION env variable
        run: |
          VERSION=$(cat VERSION)
          echo set VERSION=$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Test with Maven (and maybe Deploy)
        shell: bash
        run: mvn deploy ${{ env.MAVEN_CLI_OPTS}}
        env:
          MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - name: Merge JaCoCo execution files
        shell: bash
        run: mvn jacoco:merge@merge -N

      - name: Generate aggregate coverage report
        shell: bash
        run: mvn jacoco:report -Djacoco.dataFile=${{ github.workspace }}/target/jacoco.exec

      - name: Set SONAR_SCANNER_OPTS
        shell: bash
        run: |
          echo "SONAR_SCANNER_OPTS=sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=activiti -Dsonar.projectKey=Activiti_Activiti -Dsonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco*/jacoco.xml" >> $GITHUB_ENV

      - name: Run SonarCloud analysis
        if: ${{ env.SONAR_TOKEN != '' }}
        shell: bash
        run: mvn ${{ env.SONAR_SCANNER_OPTS }} ${{ env.MAVEN_CLI_OPTS}}
        env:
          MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Echo Longest Test Run
        uses: ./.github/actions/echo-longest-run

      - name: Configure git user
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@users.noreply.github.com
        env:
          GITHUB_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}

      - name: Create release tag
        run: |
          git commit -am "Release $VERSION" --allow-empty
          git tag -fa $VERSION -m "Release version $VERSION"
          git push -f -q origin $VERSION

      - name: Get branch name
        uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@bebd6c2fddd0a58ecf7f0acfc511a019f6afc180 # v9.2.0

      - name: Propagate
        uses: Alfresco/alfresco-build-tools/.github/actions/jx-updatebot-pr@bebd6c2fddd0a58ecf7f0acfc511a019f6afc180 # v9.2.0
        if: ${{ env.BRANCH_NAME == 'develop' }}
        env:
          DEVELOPMENT_BRANCH: ${{ github.ref_name }}
        with:
          version: ${{ env.VERSION }}
          auto-merge: "true"
          labels: ${{ env.DEVELOPMENT_BRANCH }}
          base-branch-name: ${{ env.DEVELOPMENT_BRANCH }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          git-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-author-name: ${{ secrets.BOT_GITHUB_USERNAME }}

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always() && failure()
    steps:
      - name: Teams Notification
        uses: Alfresco/alfresco-build-tools/.github/actions/send-teams-notification@bebd6c2fddd0a58ecf7f0acfc511a019f6afc180 # v9.2.0
        with:
          webhook-url: ${{ secrets.TEAMS_NOTIFICATION_WORKFLOW_WEBHOOK }}
